/**
 * Context Selector
 *
 * When transitioning between tasks (new todo list created after a previous task completed),
 * this module uses the selection model to decide which previous turns are relevant to the
 * new task. Instead of compressing everything into a text summary, it preserves the original
 * turn data (output.json files) and creates a reference file (context_refs.json) pointing
 * to the selected turns.
 *
 * Flow:
 * 1. Scan per-turn output files from the previous task's timestamp directory
 * 2. Build compact summaries of each turn (assistant response + tool calls)
 * 3. Send summaries + new todo list to the selection model in batches
 * 4. Model returns which turns are relevant
 * 5. Save selected turn paths to context_refs.json
 *
 * Loading:
 * 1. Read context_refs.json
 * 2. Load referenced output.json files
 * 3. Format as <previous_context> blocks for injection into conversation history
 */

import * as fs from "fs/promises"
import * as path from "path"

import Anthropic from "@anthropic-ai/sdk"

import { ApiHandler } from "../../api"
import { tiktoken } from "../../utils/tiktoken"
import { getTaskDirectoryPath } from "../../utils/storage"
import {
	type TurnOutput,
	saveTurnOutput,
	generateTaskTimestamp,
	assembleTurns,
} from "../task-persistence/turn-persistence"
import type { Task } from "../task/Task"
import type { TodoItem } from "@roo-code/types"
import type { ApiMessage } from "../task-persistence/apiMessages"

// Reserve tokens for: system prompt + todo list + output buffer
const RESERVED_TOKENS = 3000
// Fallback context window size
const DEFAULT_CONTEXT_WINDOW = 32_000
// Max chars of assistant message to include in compact summary sent to selection model
const SUMMARY_PREVIEW_CHARS = 600

const CONTEXT_REFS_FILENAME = "context_refs.json"
const CONTEXT_SUMMARY_FILENAME = "context_summary.json"

// ── Types ──────────────────────────────────────────────────────────────────

export interface ContextRef {
	/** Relative path from task base dir to the output.json file */
	relativePath: string
	/** Turn number from the output.json */
	turnNumber: number
	/** Todo item this turn was working on */
	todoItemContent?: string
	/** Model's reason for selecting this turn */
	reason?: string
}

export interface ContextRefsFile {
	createdAt: number
	taskTimestamp: string
	newTodoItems: string[]
	selectedTurns: ContextRef[]
}

/** Persisted summary of all old messages, generated alongside context selection. */
export interface ContextSummaryFile {
	createdAt: number
	taskTimestamp: string
	/** Condensed summary text of all old messages */
	summaryText: string
	/** Number of old messages that were summarized */
	originalMessageCount: number
}

/** Detailed turn data for UI display (passed to todo_item_divider) */
export interface DetailedTurn {
	turnNumber: number
	todoItemContent?: string
	reason?: string
	/** Full assistant message text */
	assistantMessage: string
	/** Tool names called */
	toolNames: string[]
}

export interface ContextSelectionResult {
	/** Display-friendly summary text */
	summary: string
	/** Detailed turn data for expandable UI */
	turns: DetailedTurn[]
	/** Condensed summary of ALL old messages (generated by condensing model) */
	contextSummaryText?: string
}

/** A single context block loaded from a selected turn. Each block is independent and can be individually included/excluded by the knapsack fitter. */
export interface ContextBlock {
	/** Reference info from context_refs.json */
	ref: ContextRef
	/** Independent user+assistant message pair for this turn */
	messages: ApiMessage[]
	/** Token count for this block's messages */
	tokenCount: number
}

interface TurnSummary {
	turnNumber: number
	todoItemContent?: string
	/** Compact preview of assistant response */
	assistantPreview: string
	/** Tool names called in this turn */
	toolNames: string[]
	/** Full relative path to the output.json */
	relativePath: string
	/** Token count for this summary entry */
	tokenCount?: number
}

// ── Selection Model Prompt ────────────────────────────────────────────────

const SELECTION_SYSTEM_PROMPT = `你是一个严格的上下文筛选助手。你会收到一系列之前任务的消息摘要和一个当前任务列表。
你必须严格以当前任务列表为核心标准，只选择与当前任务直接相关的消息。

## 筛选原则（按优先级排序）
1. **任务相关性优先**：消息必须与当前任务列表中的某个具体任务直接相关，reason 中必须明确指出关联的任务项
2. **问题预防**：消息中记录的错误、陷阱、已知限制与当前任务可能遇到的问题相同，避免重复犯错
3. **代码依赖**：消息中修改/创建的文件、函数、接口被当前任务依赖
4. **架构约束**：消息中包含的设计决策会约束当前任务的实现方式

## 严格排除
- 与当前任务列表无关的操作，即使它们本身很重要
- 已完成且不影响当前任务的调试记录
- 重复的消息（只保留最终版本）
- 纯粹的探索性操作（如只读文件但未产生决策）

## 输出格式
JSON 数组，每项的 reason 必须明确说明与哪个任务项相关：
[
  {"turn": 3, "reason": "[任务: 实现用户注册] AuthService 的 JWT 实现，注册功能需要复用"},
  {"turn": 7, "reason": "[任务: 修复登录bug] 记录了 token 过期处理的已知问题"}
]

只输出 JSON 数组，不要其他文字。`

// ── Scanning ──────────────────────────────────────────────────────────────

/**
 * Scan the task's turn directory for all output.json files.
 * Returns TurnSummary objects with compact previews for the selection model.
 */
async function scanTurnFiles(globalStoragePath: string, taskId: string, taskTimestamp: string): Promise<TurnSummary[]> {
	const taskDir = await getTaskDirectoryPath(globalStoragePath, taskId)
	const taskBaseDir = path.join(taskDir, "task")

	// Discover which timestamp folders to scan.
	// Primary: the specified taskTimestamp. Fallback: scan ALL timestamp folders
	// (handles case where taskTimestamp was regenerated on resume and doesn't match turn files).
	let timestampsToScan: string[] = [taskTimestamp]
	try {
		const primaryDir = path.join(taskBaseDir, taskTimestamp)
		const primaryEntries = await fs.readdir(primaryDir)
		const hasTurnDirs = primaryEntries.some((e) => !e.endsWith(".json"))
		if (!hasTurnDirs) {
			// Primary timestamp has no turn data — scan all timestamps
			const allTimestamps = await fs.readdir(taskBaseDir)
			timestampsToScan = allTimestamps.filter((d) => /^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}$/.test(d))
			console.log(
				`[scanTurnFiles] Primary timestamp ${taskTimestamp} empty, scanning all: ${timestampsToScan.join(", ")}`,
			)
		}
	} catch {
		// Primary dir doesn't exist — scan all timestamps
		try {
			const allTimestamps = await fs.readdir(taskBaseDir)
			timestampsToScan = allTimestamps.filter((d) => /^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}$/.test(d))
			console.log(
				`[scanTurnFiles] Primary timestamp ${taskTimestamp} not found, scanning all: ${timestampsToScan.join(", ")}`,
			)
		} catch {
			return []
		}
	}

	const summaries: TurnSummary[] = []

	for (const ts of timestampsToScan) {
		const baseDir = path.join(taskBaseDir, ts)
		try {
			const itemDirs = await fs.readdir(baseDir)

			for (const itemDir of itemDirs) {
				if (!itemDir || itemDir.endsWith(".json")) continue

				const itemPath = path.join(baseDir, itemDir)
				const stat = await fs.stat(itemPath)
				if (!stat.isDirectory()) continue

				// List turn folders (消息1, 消息2, ...)
				const turnDirs = await fs.readdir(itemPath)
				const messageDirs = turnDirs
					.filter((d) => /^消息\d+$/.test(d))
					.sort((a, b) => {
						const numA = parseInt(a.replace("消息", ""), 10)
						const numB = parseInt(b.replace("消息", ""), 10)
						return numA - numB
					})

				for (const msgDir of messageDirs) {
					const outputPath = path.join(itemPath, msgDir, "output.json")
					// Include timestamp in relativePath so loadContextBlocks can find the file
					const relativePath = path.join(ts, itemDir, msgDir, "output.json")

					try {
						const content = await fs.readFile(outputPath, "utf8")
						const turnOutput = JSON.parse(content) as TurnOutput

						// Build compact summary
						const assistantMsg = turnOutput.output?.assistantMessage || ""
						const toolCalls = turnOutput.output?.toolCalls || []
						const toolNames = toolCalls.map((tc: any) => tc.name || "unknown")

						summaries.push({
							turnNumber: turnOutput.turnNumber,
							todoItemContent: turnOutput.todoItemContent,
							assistantPreview: assistantMsg.substring(0, SUMMARY_PREVIEW_CHARS),
							toolNames,
							relativePath,
						})
					} catch {
						// Skip unreadable files
					}
				}
			}
		} catch {
			// Timestamp directory doesn't exist or can't be read
		}
	}

	// Sort by turn number
	summaries.sort((a, b) => a.turnNumber - b.turnNumber)

	return summaries
}

/**
 * Filter turn summaries to only include the most recent N distinct tasks (by todoItemContent).
 * Tasks are ordered by the highest turn number they contain (most recent first).
 * @param maxTasks Read from task.contextRetentionTasks (VS Code setting "contextRetentionTasks")
 */
function filterToRecentTasks(summaries: TurnSummary[], maxTasks: number): TurnSummary[] {
	if (summaries.length === 0) return summaries

	// Group turns by todoItemContent, tracking the max turn number per task
	const taskGroups = new Map<string, { maxTurn: number; turns: TurnSummary[] }>()
	for (const s of summaries) {
		const key = s.todoItemContent || "__no_task__"
		const group = taskGroups.get(key)
		if (group) {
			group.maxTurn = Math.max(group.maxTurn, s.turnNumber)
			group.turns.push(s)
		} else {
			taskGroups.set(key, { maxTurn: s.turnNumber, turns: [s] })
		}
	}

	if (taskGroups.size <= maxTasks) return summaries

	// Sort tasks by their most recent turn number (descending) and take the last N
	const sortedTasks = Array.from(taskGroups.entries()).sort((a, b) => b[1].maxTurn - a[1].maxTurn)
	const recentTasks = new Set(sortedTasks.slice(0, maxTasks).map(([key]) => key))

	const filtered = summaries.filter((s) => recentTasks.has(s.todoItemContent || "__no_task__"))
	console.log(
		`[filterToRecentTasks] Kept ${filtered.length}/${summaries.length} turns from ${maxTasks}/${taskGroups.size} tasks`,
	)
	return filtered
}

// ── Formatting ────────────────────────────────────────────────────────────

/**
 * Format a turn summary for the selection model prompt.
 */
function formatTurnSummary(summary: TurnSummary): string {
	const lines: string[] = []
	lines.push(`Turn ${summary.turnNumber}${summary.todoItemContent ? ` [项目: ${summary.todoItemContent}]` : ""}:`)
	if (summary.assistantPreview) {
		lines.push(
			`  Response: ${summary.assistantPreview}${summary.assistantPreview.length >= SUMMARY_PREVIEW_CHARS ? "..." : ""}`,
		)
	}
	if (summary.toolNames.length > 0) {
		lines.push(`  Tools: ${summary.toolNames.join(", ")}`)
	}
	return lines.join("\n")
}

/**
 * Format the new todo list for the selection prompt.
 */
function formatNewTodoList(todos: TodoItem[]): string {
	return todos
		.map((t) => {
			let box = "[ ]"
			if (t.status === "completed") box = "[x]"
			else if (t.status === "in_progress") box = "[-]"
			return `${box} ${t.content}`
		})
		.join("\n")
}

// ── Selection ─────────────────────────────────────────────────────────────

/**
 * Count tokens for a text string.
 */
async function countTextTokens(text: string): Promise<number> {
	return tiktoken([{ type: "text", text }])
}

/**
 * Pack turn summaries into batches that fit within the model's context window.
 */
async function packSummariesIntoBatches(summaries: TurnSummary[], capacity: number): Promise<TurnSummary[][]> {
	// Count tokens for each summary
	for (const summary of summaries) {
		const text = formatTurnSummary(summary)
		summary.tokenCount = await countTextTokens(text)
	}

	const batches: TurnSummary[][] = []
	let currentBatch: TurnSummary[] = []
	let currentSize = 0

	for (const summary of summaries) {
		const tokens = summary.tokenCount || 0

		if (currentSize + tokens > capacity && currentBatch.length > 0) {
			batches.push(currentBatch)
			currentBatch = []
			currentSize = 0
		}

		currentBatch.push(summary)
		currentSize += tokens
	}

	if (currentBatch.length > 0) {
		batches.push(currentBatch)
	}

	return batches
}

/**
 * Call the selection model to pick relevant turns from a batch.
 */
async function callSelectionModel(apiHandler: ApiHandler, systemPrompt: string, userMessage: string): Promise<string> {
	const messages: Anthropic.Messages.MessageParam[] = [{ role: "user", content: userMessage }]

	let result = ""
	const stream = apiHandler.createMessage(systemPrompt, messages)

	for await (const chunk of stream) {
		if (chunk.type === "text") {
			result += chunk.text
		}
	}

	return result.trim()
}

/**
 * Parse the selection model's response to extract selected turn numbers.
 */
function parseSelectionResponse(response: string): { turn: number; reason?: string }[] {
	// Try to extract JSON array from the response
	const jsonMatch = response.match(/\[[\s\S]*\]/)
	if (!jsonMatch) return []

	try {
		const parsed = JSON.parse(jsonMatch[0])
		if (!Array.isArray(parsed)) return []

		return parsed
			.filter((item: any) => typeof item.turn === "number")
			.map((item: any) => ({
				turn: item.turn,
				reason: item.reason,
			}))
	} catch {
		return []
	}
}

// ── Main Entry Points ─────────────────────────────────────────────────────

/**
 * Select relevant turns from the previous task and save references.
 *
 * Called during todo list transition (update_todo_list with shouldCompress=true).
 * Replaces the old generateTodoTransitionContext approach.
 *
 * @returns The context refs file content, or undefined if no turns were found/selected
 */
export async function selectAndSaveContextRefs(task: Task, newTodos: TodoItem[]): Promise<ContextRefsFile | undefined> {
	const taskTimestamp = task.taskTimestamp
	if (!taskTimestamp) {
		console.log("[ContextSelector] No taskTimestamp, skipping selection")
		return undefined
	}

	// 1. Scan turn files and filter to recent tasks
	const allSummaries = await scanTurnFiles(task.globalStoragePath, task.taskId, taskTimestamp)
	const summaries = filterToRecentTasks(allSummaries, task.contextRetentionTasks)
	if (summaries.length === 0) {
		console.log("[ContextSelector] No turn files found, skipping selection")
		return undefined
	}

	console.log(`[ContextSelector] Found ${summaries.length} turns to evaluate`)

	// 2. Get selection model
	const apiHandler = await task.getCondensingApiHandler()
	const modelInfo = apiHandler.getModel().info
	const contextWindow = modelInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	const capacity = contextWindow - RESERVED_TOKENS

	// 3. Pack summaries into batches
	const batches = await packSummariesIntoBatches(summaries, capacity)
	console.log(`[ContextSelector] Packed into ${batches.length} batch(es)`)

	// 4. Send each batch to selection model
	const allSelections: { turn: number; reason?: string }[] = []
	const todoListText = formatNewTodoList(newTodos)

	for (let batchIdx = 0; batchIdx < batches.length; batchIdx++) {
		const batch = batches[batchIdx]
		const summaryTexts = batch.map(formatTurnSummary).join("\n\n")

		const userMessage = `以下是之前任务的消息列表：

${summaryTexts}

新的任务列表：
${todoListText}

请选择哪些消息与新任务相关，应该被保留作为上下文。`

		try {
			const response = await callSelectionModel(apiHandler, SELECTION_SYSTEM_PROMPT, userMessage)
			const selections = parseSelectionResponse(response)
			allSelections.push(...selections)
			console.log(`[ContextSelector] Batch ${batchIdx + 1}: selected ${selections.length} turns`)
		} catch (err) {
			console.warn(`[ContextSelector] Batch ${batchIdx + 1} failed:`, err)
		}
	}

	if (allSelections.length === 0) {
		console.log("[ContextSelector] No turns selected by model")
		return undefined
	}

	// 5. Build context refs
	const selectedTurns: ContextRef[] = []
	for (const selection of allSelections) {
		const summary = summaries.find((s) => s.turnNumber === selection.turn)
		if (summary) {
			selectedTurns.push({
				relativePath: summary.relativePath,
				turnNumber: summary.turnNumber,
				todoItemContent: summary.todoItemContent,
				reason: selection.reason,
			})
		}
	}

	const contextRefs: ContextRefsFile = {
		createdAt: Date.now(),
		taskTimestamp,
		newTodoItems: newTodos.map((t) => t.content),
		selectedTurns,
	}

	// 6. Save context_refs.json to summary/context/<timestamp>/
	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	const contextDir = path.join(taskDir, "summary", "context", taskTimestamp)
	await fs.mkdir(contextDir, { recursive: true })
	const refsPath = path.join(contextDir, CONTEXT_REFS_FILENAME)
	await fs.writeFile(refsPath, JSON.stringify(contextRefs, null, 2), "utf8")

	console.log(`[ContextSelector] Saved ${selectedTurns.length} turn references to ${refsPath}`)

	// Store the refs path on the task for easy access during context building
	task.contextRefsPath = refsPath

	return contextRefs
}

/**
 * Load context refs and build context messages for injection into conversation history.
 *
 * Called during attemptApiRequest to prepend relevant previous context.
 *
 * @returns Array of ApiMessages to prepend, or empty array if no refs exist
 */
export async function loadContextAsMessages(task: Task): Promise<ApiMessage[]> {
	if (!task.contextRefsPath) {
		return []
	}

	let refsFile: ContextRefsFile
	try {
		const content = await fs.readFile(task.contextRefsPath, "utf8")
		refsFile = JSON.parse(content) as ContextRefsFile
	} catch {
		return []
	}

	if (!refsFile.selectedTurns || refsFile.selectedTurns.length === 0) {
		return []
	}

	// Load each referenced output.json and extract the assistant's response
	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	// relativePath already includes the timestamp prefix (e.g., "2026-03-15_22-00-00/item/消息1/output.json")
	const baseDir = path.join(taskDir, "task")

	const contextBlocks: string[] = []

	for (const ref of refsFile.selectedTurns) {
		const outputPath = path.join(baseDir, ref.relativePath)

		try {
			const content = await fs.readFile(outputPath, "utf8")
			const turnOutput = JSON.parse(content) as TurnOutput

			const assistantMsg = turnOutput.output?.assistantMessage || ""
			const toolCalls = turnOutput.output?.toolCalls || []

			// Format this turn's contribution
			const lines: string[] = []
			lines.push(`--- Turn ${ref.turnNumber}${ref.todoItemContent ? ` [${ref.todoItemContent}]` : ""} ---`)
			if (assistantMsg) {
				lines.push(assistantMsg)
			}
			if (toolCalls.length > 0) {
				const toolSummary = toolCalls
					.map((tc: any) => {
						const name = tc.name || "unknown"
						const params = tc.input || {}
						// Show key parameter values for context
						const paramKeys = Object.keys(params).slice(0, 3)
						const paramStr = paramKeys
							.map((k) => {
								const val = String(params[k] || "").substring(0, 100)
								return `${k}=${val}`
							})
							.join(", ")
						return `[${name}(${paramStr})]`
					})
					.join("\n")
				lines.push(toolSummary)
			}

			contextBlocks.push(lines.join("\n"))
		} catch {
			// Skip unreadable files
		}
	}

	if (contextBlocks.length === 0) {
		return []
	}

	// Build a single user+assistant pair with the previous context
	const contextText = contextBlocks.join("\n\n")

	const userMessage: ApiMessage = {
		role: "user",
		content: [
			{
				type: "text",
				text: `<previous_context source="selected_turns">\n${contextText}\n</previous_context>`,
			},
		],
		ts: Date.now(),
		isSummary: true,
		isContextSummary: true,
	}

	const assistantMessage: ApiMessage = {
		role: "assistant",
		content: [
			{
				type: "text",
				text: "I have reviewed the selected context from the previous task. I'm ready to proceed with the new tasks.",
			},
		],
		ts: Date.now(),
		isContextSummary: true,
	}

	return [userMessage, assistantMessage]
}

// ── History Management ────────────────────────────────────────────────────

/**
 * Find the boundary index where the user's current (new) request starts.
 * Everything before this index belongs to the old task.
 * Everything from this index onward is the current conversation turn and must be preserved.
 */
function findPreserveBoundary(messages: ApiMessage[]): number {
	for (let i = messages.length - 1; i >= 0; i--) {
		const msg = messages[i]
		if (msg.role !== "user") continue

		const content = msg.content
		if (typeof content === "string" && content.trim().length > 0) {
			return i
		}
		if (Array.isArray(content)) {
			const hasUserText = content.some((block: any) => {
				if (block.type !== "text") return false
				const text = block.text?.trim() || ""
				if (text.startsWith("<environment_details>")) return false
				return text.length > 0
			})
			if (hasUserText) return i
		}
	}
	return messages.length
}

/**
 * Load detailed turn content for UI display.
 */
async function loadDetailedTurns(
	globalStoragePath: string,
	taskId: string,
	refsFile: ContextRefsFile,
): Promise<DetailedTurn[]> {
	const taskDir = await getTaskDirectoryPath(globalStoragePath, taskId)
	// relativePath already includes the timestamp prefix from scanTurnFiles
	const baseDir = path.join(taskDir, "task")
	const result: DetailedTurn[] = []

	for (const ref of refsFile.selectedTurns) {
		const outputPath = path.join(baseDir, ref.relativePath)
		try {
			const content = await fs.readFile(outputPath, "utf8")
			const turnOutput = JSON.parse(content) as TurnOutput
			const toolCalls = turnOutput.output?.toolCalls || []
			const toolNames = toolCalls.map((tc: any) => tc.name || "unknown")
			const parts: string[] = []

			const rawText = turnOutput.output?.assistantMessage || ""
			console.log(
				`[loadDetailedTurns] Turn ${ref.turnNumber}: file=${outputPath}, fileSize=${content.length}, assistantMsg=${rawText.length}chars, toolCalls=${toolCalls.length}`,
			)

			// Include assistant text if present
			if (rawText.trim()) {
				parts.push(rawText)
			}

			// Append comprehensive tool call details
			for (const tc of toolCalls) {
				const name = tc.name || "unknown"
				const params = (tc as any).input || {}
				const paramEntries = Object.entries(params)
				const lines: string[] = [`── ${name} ──`]
				for (const [key, rawVal] of paramEntries) {
					const val = String(rawVal ?? "")
					lines.push(`  ${key}: ${val}`)
				}
				parts.push(lines.join("\n"))
			}

			// Load tool results from separate tools_消息N/output.json (or legacy toolResults field)
			let toolResultItems: any[] = turnOutput.output?.toolResults || []
			if (toolResultItems.length === 0) {
				// Try reading from separate tools_消息N/output.json file
				const turnDir = path.dirname(outputPath)
				const parentDir = path.dirname(turnDir)
				const toolsDir = path.join(parentDir, `tools_消息${ref.turnNumber}`)
				try {
					const toolsContent = await fs.readFile(path.join(toolsDir, "output.json"), "utf8")
					const toolsData = JSON.parse(toolsContent)
					toolResultItems = toolsData.toolResults || []
				} catch {
					// No tools_消息N file — expected for old data or text-only turns
				}
			}
			if (toolResultItems.length > 0) {
				parts.push(`── tool results ──`)
				for (const tr of toolResultItems) {
					const resultContent = Array.isArray(tr.content)
						? tr.content.map((b: any) => b.text || "").join("\n")
						: String(tr.content ?? "")
					if (resultContent.trim()) {
						parts.push(resultContent)
					}
				}
			}

			const assembled = parts.join("\n\n")
			console.log(`[loadDetailedTurns] Turn ${ref.turnNumber}: assembledMessage=${assembled.length}chars`)

			result.push({
				turnNumber: ref.turnNumber,
				todoItemContent: ref.todoItemContent,
				reason: ref.reason,
				assistantMessage: assembled,
				toolNames,
			})
		} catch (err) {
			console.warn(`[loadDetailedTurns] Turn ${ref.turnNumber}: FAILED to read ${outputPath}:`, err)
		}
	}

	return result
}

/**
 * Full context selection flow: select relevant turns, load them, and replace old history.
 *
 * 1. Calls selectAndSaveContextRefs to scan turns and ask the model which are relevant
 * 2. Loads selected turns as ApiMessage pairs
 * 3. Finds the preserve boundary (current request messages)
 * 4. Replaces apiConversationHistory with [context messages + current request messages]
 *
 * @returns Structured result with summary + detailed turns for UI, or undefined if nothing selected
 */
export async function applyContextSelection(
	task: Task,
	newTodos: TodoItem[],
): Promise<ContextSelectionResult | undefined> {
	// 1. Select and save refs
	const refs = await selectAndSaveContextRefs(task, newTodos)
	if (!refs || refs.selectedTurns.length === 0) {
		return undefined
	}

	// 2. Load selected turns as context messages
	const contextMessages = await loadContextAsMessages(task)
	if (contextMessages.length === 0) {
		return undefined
	}

	// 3. Find preserve boundary in current history
	const allMessages = task.apiConversationHistory
	const preserveBoundary = findPreserveBoundary(allMessages)
	const messagesToPreserve = allMessages.slice(preserveBoundary)
	const messagesToSummarize = allMessages.slice(0, preserveBoundary)

	// 4. Generate and persist a condensed summary from turn files on disk
	let summaryMessages: ApiMessage[] = []
	let generatedSummaryText: string | undefined
	try {
		generatedSummaryText = await generateSummaryFromTurns(task, newTodos)
		if (generatedSummaryText) {
			await saveContextSummary(task, generatedSummaryText, messagesToSummarize.length)
			summaryMessages = buildContextSummaryMessages(generatedSummaryText)
			console.log(`[ContextSelector] Generated summary from turn files (${generatedSummaryText.length} chars)`)
		}
	} catch (err) {
		console.warn("[ContextSelector] Failed to generate summary from turns (non-critical):", err)
	}

	console.log(
		`[ContextSelector] Replacing ${preserveBoundary} old messages with ${contextMessages.length} context messages + ${summaryMessages.length} summary messages, preserving ${messagesToPreserve.length} current messages`,
	)

	// 5. Replace history: [selected context blocks] + [summary] + [current request messages]
	await task.overwriteApiConversationHistory([...contextMessages, ...summaryMessages, ...messagesToPreserve])

	// Reset boundaries since old messages are gone
	task.todoItemBoundaries.clear()

	// 6. Load detailed turns for UI display
	const detailedTurns = await loadDetailedTurns(task.globalStoragePath, task.taskId, refs)

	// 7. Build summary text
	const summaryLines = refs.selectedTurns.map((ref) => {
		const label = ref.todoItemContent ? `Turn ${ref.turnNumber} [${ref.todoItemContent}]` : `Turn ${ref.turnNumber}`
		return ref.reason ? `• ${label}: ${ref.reason}` : `• ${label}`
	})
	const summary = `已引用 ${refs.selectedTurns.length} 条历史消息:\n${summaryLines.join("\n")}`

	return { summary, turns: detailedTurns, contextSummaryText: generatedSummaryText }
}

/**
 * Refresh context selection for subsequent todo item transitions.
 * Re-scans turn files, re-selects relevant turns based on new todos,
 * and re-generates the conversation summary.
 * Does NOT replace history — Phase 2 (injectContextBlocks) picks up
 * the updated context_refs.json and context_summary.json automatically.
 */
export async function refreshContextSelection(
	task: Task,
	newTodos: TodoItem[],
): Promise<ContextSelectionResult | undefined> {
	// 1. Try to re-scan turn files and re-select with new todos
	let refs: ContextRefsFile | undefined
	try {
		refs = await selectAndSaveContextRefs(task, newTodos)
	} catch (err) {
		console.warn("[refreshContextSelection] Re-selection failed, will fall back to existing refs:", err)
	}

	// 2. If re-selection yielded no results, fall back to loading existing context_refs.json from disk
	if (!refs || refs.selectedTurns.length === 0) {
		if (task.contextRefsPath) {
			try {
				const content = await fs.readFile(task.contextRefsPath, "utf8")
				refs = JSON.parse(content) as ContextRefsFile
				console.log(
					`[refreshContextSelection] Fell back to existing refs: ${refs.selectedTurns?.length ?? 0} turns`,
				)
			} catch {
				console.warn("[refreshContextSelection] Failed to load existing refs from disk")
			}
		}
	}

	if (!refs || !refs.selectedTurns || refs.selectedTurns.length === 0) {
		return undefined
	}

	// 3. Re-generate summary from turn files on disk
	let contextSummaryText: string | undefined
	try {
		contextSummaryText = await generateSummaryFromTurns(task, newTodos)
		if (contextSummaryText) {
			const coreCount = task.apiConversationHistory.filter((m) => !m.isContextBlock && !m.isContextSummary).length
			await saveContextSummary(task, contextSummaryText, coreCount)
			console.log(
				`[refreshContextSelection] Updated summary from turn files (${contextSummaryText.length} chars)`,
			)
		}
	} catch (err) {
		console.warn("[refreshContextSelection] Summary generation failed (non-critical):", err)
	}

	// 4. If summary generation failed/skipped, try loading existing summary from disk
	if (!contextSummaryText && task.taskTimestamp) {
		try {
			const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
			const summaryPath = path.join(taskDir, "summary", "context", task.taskTimestamp, CONTEXT_SUMMARY_FILENAME)
			const summaryContent = await fs.readFile(summaryPath, "utf8")
			const summaryFile = JSON.parse(summaryContent) as ContextSummaryFile
			contextSummaryText = summaryFile.summaryText
			console.log("[refreshContextSelection] Loaded existing summary from disk")
		} catch {
			// No existing summary — expected for first run
		}
	}

	// 5. Load detailed turns for UI
	const detailedTurns = await loadDetailedTurns(task.globalStoragePath, task.taskId, refs)

	// 6. Build summary text
	const summaryLines = refs.selectedTurns.map((ref) => {
		const label = ref.todoItemContent ? `Turn ${ref.turnNumber} [${ref.todoItemContent}]` : `Turn ${ref.turnNumber}`
		return ref.reason ? `• ${label}: ${ref.reason}` : `• ${label}`
	})
	const summary = `已引用 ${refs.selectedTurns.length} 条历史消息:\n${summaryLines.join("\n")}`

	return { summary, turns: detailedTurns, contextSummaryText }
}

// ── Context Block Loading & Knapsack Fitting ─────────────────────────────

const TRANSITION_SYSTEM_PROMPT = `你是一个严格的上下文筛选助手。你会收到一系列之前任务的消息摘要。
你的工作是筛选出对后续工作有实际价值的消息，宁缺毋滥。

## 筛选原则（按优先级排序）
1. **持久影响**：消息中的操作产生了持久性影响（如创建/修改了文件、确立了架构模式、安装了依赖）
2. **可复用知识**：消息中包含可被后续任务复用的技术方案或接口设计
3. **问题记录**：消息中记录了重要的已知问题、限制条件或技术债务

## 严格排除
- 纯粹的文件阅读或探索（未产生决策或修改）
- 调试过程中的中间尝试（只保留最终解决方案）
- 重复的消息（只保留最终版本）
- 临时性操作（如临时日志、测试输出）

## 输出格式
JSON 数组，reason 必须具体说明保留价值：
[
  {"turn": 3, "reason": "确立了 MVC 架构模式，后续功能开发必须遵循"},
  {"turn": 7, "reason": "修改了数据库 schema，影响所有数据访问层"}
]

只输出 JSON 数组，不要其他文字。`

/**
 * Load each selected turn from context_refs.json as an independent ContextBlock.
 * Each block contains its own user+assistant message pair and token count.
 */
export async function loadContextBlocks(task: Task): Promise<ContextBlock[]> {
	if (!task.contextRefsPath) return []

	let refsFile: ContextRefsFile
	try {
		const content = await fs.readFile(task.contextRefsPath, "utf8")
		refsFile = JSON.parse(content) as ContextRefsFile
	} catch {
		return []
	}

	if (!refsFile.selectedTurns || refsFile.selectedTurns.length === 0) return []

	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	// relativePath already includes the timestamp prefix from scanTurnFiles
	const baseDir = path.join(taskDir, "task")
	const blocks: ContextBlock[] = []

	for (const ref of refsFile.selectedTurns) {
		const outputPath = path.join(baseDir, ref.relativePath)
		try {
			const content = await fs.readFile(outputPath, "utf8")
			const turnOutput = JSON.parse(content) as TurnOutput

			const assistantMsg = turnOutput.output?.assistantMessage || ""
			const toolCalls = turnOutput.output?.toolCalls || []

			// Build turn content
			const lines: string[] = []
			lines.push(`--- Turn ${ref.turnNumber}${ref.todoItemContent ? ` [${ref.todoItemContent}]` : ""} ---`)
			if (assistantMsg) lines.push(assistantMsg)
			if (toolCalls.length > 0) {
				const toolSummary = toolCalls
					.map((tc: any) => {
						const name = tc.name || "unknown"
						const params = tc.input || {}
						const paramKeys = Object.keys(params).slice(0, 3)
						const paramStr = paramKeys
							.map((k) => {
								const val = String(params[k] || "").substring(0, 100)
								return `${k}=${val}`
							})
							.join(", ")
						return `[${name}(${paramStr})]`
					})
					.join("\n")
				lines.push(toolSummary)
			}

			const turnContent = lines.join("\n")

			const userMsg: ApiMessage = {
				role: "user",
				content: [
					{
						type: "text",
						text: `<previous_context turn="${ref.turnNumber}">\n${turnContent}\n</previous_context>`,
					},
				],
				ts: Date.now(),
				isSummary: true,
				isContextBlock: true,
			}

			const assistantReply: ApiMessage = {
				role: "assistant",
				content: [{ type: "text", text: "Noted." }],
				ts: Date.now(),
				isContextBlock: true,
			}

			const tokenCount = (await countMessageTokens(userMsg)) + (await countMessageTokens(assistantReply))

			blocks.push({
				ref,
				messages: [userMsg, assistantReply],
				tokenCount,
			})
		} catch {
			// Skip unreadable files
		}
	}

	return blocks
}

/**
 * Greedy knapsack: fit context blocks into the available token budget.
 * Blocks are tried in order (by turn number). If a block doesn't fit, it's skipped but not discarded.
 */
export function fitContextBlocks(
	blocks: ContextBlock[],
	budgetTokens: number,
): { included: ContextBlock[]; excluded: ContextBlock[] } {
	const included: ContextBlock[] = []
	const excluded: ContextBlock[] = []
	let remaining = budgetTokens

	for (const block of blocks) {
		if (block.tokenCount <= remaining) {
			included.push(block)
			remaining -= block.tokenCount
		} else {
			excluded.push(block)
		}
	}

	return { included, excluded }
}

/**
 * Selection-only phase: scan turn files, ask AI which are relevant, save context_refs.json.
 * Does NOT replace conversation history — that's handled by injectContextBlocks.
 *
 * Called from AttemptCompletionTool (at task completion time) to prepare context for next task.
 * Also called from attemptApiRequest as a fallback if selection wasn't done at completion time.
 *
 * @returns Number of selected turns, or 0 if nothing was selected
 */
export async function performContextSelection(task: Task): Promise<number> {
	const taskTimestamp = task.taskTimestamp
	if (!taskTimestamp) {
		console.log("[ContextSelection] No taskTimestamp, skipping")
		return 0
	}

	// 1. Scan turn files and filter to recent tasks
	const allSummaries = await scanTurnFiles(task.globalStoragePath, task.taskId, taskTimestamp)
	const summaries = filterToRecentTasks(allSummaries, task.contextRetentionTasks)
	if (summaries.length === 0) {
		console.log("[ContextSelection] No turn files found, skipping")
		return 0
	}

	console.log(`[ContextSelection] Found ${summaries.length} turns to evaluate`)

	// 2. Get selection model
	const apiHandler = await task.getCondensingApiHandler()
	const modelInfo = apiHandler.getModel().info
	const modelId = apiHandler.getModel().id
	const contextWindow = modelInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	const capacity = contextWindow - RESERVED_TOKENS
	console.log(`[ContextSelection] Using model: ${modelId}, contextWindow: ${contextWindow}, capacity: ${capacity}`)

	// 3. Pack summaries into batches
	const batches = await packSummariesIntoBatches(summaries, capacity)
	console.log(`[ContextSelection] Packed into ${batches.length} batch(es)`)

	// 4. Send each batch to selection model
	//    If todoList is available, include it in the prompt for task-aware selection
	const allSelections: { turn: number; reason?: string }[] = []
	const hasTodos = task.todoList && task.todoList.length > 0
	const systemPrompt = hasTodos ? SELECTION_SYSTEM_PROMPT : TRANSITION_SYSTEM_PROMPT
	const todoListText = hasTodos ? formatNewTodoList(task.todoList!) : ""

	for (let batchIdx = 0; batchIdx < batches.length; batchIdx++) {
		const batch = batches[batchIdx]
		const summaryTexts = batch.map(formatTurnSummary).join("\n\n")

		const userMessage = hasTodos
			? `以下是之前任务的消息列表：\n\n${summaryTexts}\n\n新的任务列表：\n${todoListText}\n\n请选择哪些消息与新任务相关，应该被保留作为上下文。`
			: `以下是之前任务的消息列表：\n\n${summaryTexts}\n\n请选择哪些消息包含重要信息，应该被保留作为后续任务的上下文。`

		try {
			console.log(`[ContextSelection] Sending batch ${batchIdx + 1}/${batches.length} (${batch.length} turns)`)
			const response = await callSelectionModel(apiHandler, systemPrompt, userMessage)
			console.log(
				`[ContextSelection] Batch ${batchIdx + 1} response (${response.length} chars): ${response.substring(0, 200)}`,
			)
			const selections = parseSelectionResponse(response)
			console.log(`[ContextSelection] Batch ${batchIdx + 1} parsed ${selections.length} selections`)
			allSelections.push(...selections)
		} catch (err) {
			console.warn(`[ContextSelection] Batch ${batchIdx + 1} failed:`, err)
		}
	}

	if (allSelections.length === 0) {
		console.log("[ContextSelection] No turns selected")
		return 0
	}

	// 5. Build and save context_refs.json
	const selectedTurns: ContextRef[] = []
	for (const selection of allSelections) {
		const summary = summaries.find((s) => s.turnNumber === selection.turn)
		if (summary) {
			selectedTurns.push({
				relativePath: summary.relativePath,
				turnNumber: summary.turnNumber,
				todoItemContent: summary.todoItemContent,
				reason: selection.reason,
			})
		}
	}

	const contextRefs: ContextRefsFile = {
		createdAt: Date.now(),
		taskTimestamp,
		newTodoItems: hasTodos ? task.todoList!.map((t) => t.content) : [],
		selectedTurns,
	}

	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	const contextDir = path.join(taskDir, "summary", "context", taskTimestamp)
	await fs.mkdir(contextDir, { recursive: true })
	const refsPath = path.join(contextDir, CONTEXT_REFS_FILENAME)
	await fs.writeFile(refsPath, JSON.stringify(contextRefs, null, 2), "utf8")
	task.contextRefsPath = refsPath

	console.log(`[ContextSelection] Saved ${selectedTurns.length} refs to ${refsPath}`)
	return selectedTurns.length
}

/**
 * Phase 1 fallback: Cross-task transition selection + history replacement.
 * Called from attemptApiRequest when needsContextCompression=true AND selection
 * wasn't already done at attempt_completion time.
 */
export async function executeTransitionSelection(task: Task): Promise<void> {
	// Run selection if not already done
	if (!task.contextRefsPath) {
		const count = await performContextSelection(task)
		if (count === 0) return
	}

	// Load blocks, fit, and replace history
	const blocks = await loadContextBlocks(task)
	if (blocks.length === 0) return

	// Calculate budget: preserve current user request messages
	const allMessages = task.apiConversationHistory
	const preserveBoundary = findPreserveBoundary(allMessages)
	const messagesToPreserve = allMessages.slice(preserveBoundary)
	const messagesToSummarize = allMessages.slice(0, preserveBoundary)

	// Generate and persist summary from turn files on disk
	let summaryMessages: ApiMessage[] = []
	try {
		const summaryText = await generateSummaryFromTurns(task)
		if (summaryText) {
			await saveContextSummary(task, summaryText, messagesToSummarize.length)
			summaryMessages = buildContextSummaryMessages(summaryText)
			console.log(`[TransitionSelection] Generated summary from turn files (${summaryText.length} chars)`)
		}
	} catch (err) {
		console.warn("[TransitionSelection] Failed to generate summary from turns (non-critical):", err)
	}

	let currentTokens = 0
	for (const msg of messagesToPreserve) {
		currentTokens += await countMessageTokens(msg)
	}
	let summaryTokens = 0
	for (const msg of summaryMessages) {
		summaryTokens += await countMessageTokens(msg)
	}

	const mainModelInfo = task.api.getModel().info
	const mainContextWindow = mainModelInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	const budget = Math.floor(mainContextWindow * BUDGET_FILL_RATIO) - currentTokens - summaryTokens

	const { included } = fitContextBlocks(blocks, budget)

	// Rebuild: [context blocks] + [summary] + [preserved messages]
	const blockMessages = included.flatMap((b) => b.messages)
	const newHistory = [...blockMessages, ...summaryMessages, ...messagesToPreserve]
	await task.overwriteApiConversationHistory(newHistory)
	task.todoItemBoundaries.clear()

	console.log(
		`[TransitionSelection] Injected ${included.length}/${blocks.length} blocks + ${summaryMessages.length > 0 ? "summary" : "no summary"}, preserved ${messagesToPreserve.length} messages`,
	)
}

/**
 * Phase 2: Dynamic context block injection.
 * Called every API call from attemptApiRequest.
 * Loads context blocks, calculates available budget, and fits blocks into history.
 */
export async function injectContextBlocks(task: Task): Promise<void> {
	if (!task.contextRefsPath) return

	const blocks = await loadContextBlocks(task)
	if (blocks.length === 0) return

	// Strip existing injected messages (context blocks + context summary)
	const coreMessages = task.apiConversationHistory.filter((m) => !m.isContextBlock && !m.isContextSummary)

	// Calculate token count of core (non-injected) messages
	let currentTokens = 0
	for (const msg of coreMessages) {
		currentTokens += await countMessageTokens(msg)
	}

	// Load persisted context summary (always included if exists, not part of knapsack budget)
	const summaryMessages = await loadContextSummaryMessages(task)
	let summaryTokens = 0
	for (const msg of summaryMessages) {
		summaryTokens += await countMessageTokens(msg)
	}

	const modelInfo = task.api.getModel().info
	const contextWindow = modelInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	const budget = Math.floor(contextWindow * BUDGET_FILL_RATIO) - currentTokens - summaryTokens

	if (budget <= 0) {
		// No budget for blocks — only inject summary if it fits
		if (
			summaryMessages.length > 0 &&
			summaryTokens + currentTokens <= Math.floor(contextWindow * BUDGET_FILL_RATIO)
		) {
			task.apiConversationHistory = [...summaryMessages, ...coreMessages]
		} else if (coreMessages.length !== task.apiConversationHistory.length) {
			task.apiConversationHistory = coreMessages
		}
		return
	}

	const { included } = fitContextBlocks(blocks, budget)

	// Rebuild: [context blocks] + [summary] + [core messages]
	const blockMessages = included.flatMap((b) => b.messages)
	task.apiConversationHistory = [...blockMessages, ...summaryMessages, ...coreMessages]
}

// ── Old Messages Summary (generated alongside context selection) ──────────

const OLD_MESSAGES_SUMMARY_PROMPT = `你是一个严格的上下文概括助手。你的目标是生成一份高度聚焦的结构化摘要，帮助 AI 助手在后续任务中快速理解项目状态。

## 概括原则
如果提供了当前任务列表，你必须：
1. **以任务列表为锚点**：每个概括段落都应明确关联到某个具体任务
2. **保留任务依赖**：当前任务需要的前置知识、已完成的基础工作、相关的文件路径和接口
3. **省略无关内容**：与当前任务列表无关的历史操作，即使重要也应省略或一笔带过
4. **突出阻塞信息**：已知的 bug、限制条件、技术债务，尤其是可能影响当前任务的

## 输出格式
按任务分组的结构化摘要：

### [任务项名称]
- 相关的已完成工作和关键决策
- 需要注意的文件路径和接口
- 已知问题或风险

### 通用项目信息
- 项目结构、技术栈、配置
- 跨任务的架构决策

要求：简洁精炼，不要冗余，不要重复，不要输出多余的解释。`

/**
 * Generate a summary from turn files on disk (the actual historical work).
 * This is the primary summary generation path — uses turn file content rather than
 * current apiConversationHistory, which may be empty or already compressed.
 */
async function generateSummaryFromTurns(task: Task, todos?: TodoItem[]): Promise<string | undefined> {
	const taskTimestamp = task.taskTimestamp
	if (!taskTimestamp) return undefined

	// Scan turn files and filter to recent tasks for a focused summary
	const allSummaries = await scanTurnFiles(task.globalStoragePath, task.taskId, taskTimestamp)
	const summaries = filterToRecentTasks(allSummaries, task.contextRetentionTasks)
	if (summaries.length === 0) return undefined

	// Build rich input from turn file content
	const turnTexts = summaries
		.map((s) => {
			const lines: string[] = []
			const header = s.todoItemContent ? `Turn ${s.turnNumber} [${s.todoItemContent}]` : `Turn ${s.turnNumber}`
			lines.push(header + ":")
			if (s.assistantPreview.trim()) {
				lines.push(s.assistantPreview)
			}
			if (s.toolNames.length > 0) {
				lines.push(`Tools used: ${s.toolNames.join(", ")}`)
			}
			return lines.join("\n")
		})
		.join("\n\n---\n\n")

	const apiHandler = await task.getCondensingApiHandler()
	const condenserInfo = apiHandler.getModel().info
	const condenserWindow = condenserInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	const batchCapacity = condenserWindow - RESERVED_TOKENS

	// Build task list context for the prompt (helps model focus on relevant info)
	let todoContext = ""
	const effectiveTodos = todos ?? task.todoList
	if (effectiveTodos && effectiveTodos.length > 0) {
		const todoLines = effectiveTodos.map((t) => {
			const status = t.status === "completed" ? "✓" : t.status === "in_progress" ? "→" : "○"
			return `${status} ${t.content}`
		})
		todoContext = `\n\n当前任务列表：\n${todoLines.join("\n")}`
	}

	const inputTokens = await tiktoken([{ type: "text", text: turnTexts }])

	let finalSummary: string

	if (inputTokens <= batchCapacity) {
		const userMessage = `以下是 AI 助手执行任务时的工作记录（共 ${summaries.length} 个轮次），请概括为结构化摘要：${todoContext}\n\n${turnTexts}`
		finalSummary = await callCompressionModel(apiHandler, OLD_MESSAGES_SUMMARY_PROMPT, userMessage)
	} else {
		// Split turns into batches
		const batchSize = Math.max(1, Math.ceil(summaries.length * (batchCapacity / inputTokens)))
		const partialSummaries: string[] = []

		for (let start = 0; start < summaries.length; start += batchSize) {
			const batch = summaries.slice(start, start + batchSize)
			const batchText = batch
				.map((s) => {
					const header = s.todoItemContent
						? `Turn ${s.turnNumber} [${s.todoItemContent}]`
						: `Turn ${s.turnNumber}`
					const lines = [header + ":"]
					if (s.assistantPreview.trim()) lines.push(s.assistantPreview)
					if (s.toolNames.length > 0) lines.push(`Tools: ${s.toolNames.join(", ")}`)
					return lines.join("\n")
				})
				.join("\n\n---\n\n")
			const batchNum = Math.floor(start / batchSize) + 1
			const userMessage = `以下是 AI 助手执行任务时的部分工作记录（第 ${batchNum} 批），请概括为结构化摘要：${todoContext}\n\n${batchText}`
			const partial = await callCompressionModel(apiHandler, OLD_MESSAGES_SUMMARY_PROMPT, userMessage)
			partialSummaries.push(partial)
		}

		finalSummary = partialSummaries.join("\n\n---\n\n")
	}

	const result = finalSummary.trim()
	console.log(`[generateSummaryFromTurns] Generated summary from ${summaries.length} turns (${result.length} chars)`)
	return result || undefined
}

/**
 * Persist the old messages summary to summary/context/<timestamp>/context_summary.json.
 */
async function saveContextSummary(task: Task, summaryText: string, originalMessageCount: number): Promise<void> {
	const taskTimestamp = task.taskTimestamp
	if (!taskTimestamp) return

	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	const contextDir = path.join(taskDir, "summary", "context", taskTimestamp)
	await fs.mkdir(contextDir, { recursive: true })

	const summaryFile: ContextSummaryFile = {
		createdAt: Date.now(),
		taskTimestamp,
		summaryText,
		originalMessageCount,
	}

	const filePath = path.join(contextDir, CONTEXT_SUMMARY_FILENAME)
	await fs.writeFile(filePath, JSON.stringify(summaryFile, null, 2), "utf8")
	console.log(`[ContextSelector] Saved context summary to ${filePath}`)
}

/**
 * Build a user+assistant message pair for the old messages summary.
 * These are injected AFTER context blocks and BEFORE the current conversation.
 */
function buildContextSummaryMessages(summaryText: string): ApiMessage[] {
	const userMsg: ApiMessage = {
		role: "user",
		content: [
			{
				type: "text",
				text: `<context_summary source="old_messages_overview">\n${summaryText}\n</context_summary>`,
			},
		],
		ts: Date.now(),
		isSummary: true,
		isContextSummary: true,
	}

	const assistantMsg: ApiMessage = {
		role: "assistant",
		content: [
			{
				type: "text",
				text: "I have reviewed the context summary of previous work. Ready to proceed.",
			},
		],
		ts: Date.now(),
		isContextSummary: true,
	}

	return [userMsg, assistantMsg]
}

/**
 * Load the persisted context summary from disk and build ApiMessage pair.
 * Used by injectContextBlocks (Phase 2) to re-inject the summary on resume.
 */
export async function loadContextSummaryMessages(task: Task): Promise<ApiMessage[]> {
	const taskTimestamp = task.taskTimestamp
	if (!taskTimestamp) return []

	const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
	const filePath = path.join(taskDir, "summary", "context", taskTimestamp, CONTEXT_SUMMARY_FILENAME)

	try {
		const content = await fs.readFile(filePath, "utf8")
		const summaryFile = JSON.parse(content) as ContextSummaryFile
		if (!summaryFile.summaryText?.trim()) return []
		return buildContextSummaryMessages(summaryFile.summaryText)
	} catch {
		return []
	}
}

// ── In-Task Context Compression ───────────────────────────────────────────

// Maximum fraction of context window to fill with all content (blocks + summary + messages).
// Used as a budget cap by Phase 1 (executeTransitionSelection) and Phase 2 (injectContextBlocks).
// Phase 3 (compressInTaskContext) uses the user-configured autoCondenseContextPercent instead.
const BUDGET_FILL_RATIO = 0.75
// After compression, keep the most recent messages (this fraction of the threshold)
const KEEP_RECENT_FRACTION = 0.4
// Minimum messages to keep uncompressed (never compress if fewer than this)
const MIN_MESSAGES_FOR_COMPRESSION = 10

/**
 * Count tokens for a single ApiMessage.
 */
async function countMessageTokens(msg: ApiMessage): Promise<number> {
	const content = msg.content
	if (typeof content === "string") {
		return tiktoken([{ type: "text", text: content }])
	}
	if (Array.isArray(content)) {
		return tiktoken(content as Anthropic.Messages.ContentBlockParam[])
	}
	return tiktoken([{ type: "text", text: String(content) }])
}

/**
 * Phase 3: Auto-condense — backpack filling + summary compression.
 *
 * Called from attemptApiRequest after Phase 2 (injectContextBlocks).
 * Controlled by user settings:
 *   - autoCondenseContext (boolean): enable/disable
 *   - autoCondenseContextPercent (number 10-100): threshold % of context window
 *
 * Strategy:
 * 1. Check if auto-condense is enabled; if not, skip.
 * 2. Strip injected messages (isContextBlock / isContextSummary) — Phase 2 will re-inject them.
 * 3. When total tokens exceed user-configured threshold:
 *    a. Create a special summary task folder (<timestamp>_summary) with the same structure as a normal task.
 *    b. Run context block selection (backpack filling) to pick relevant historical turns.
 *    c. Generate a context summary from turn files on disk.
 *    d. Save both LLM interactions as turns in the summary task folder.
 *    e. Keep only recent core messages; Phase 2 will re-inject [blocks + summary] on next API call.
 *
 * @returns true if compression was performed, false otherwise
 */
export async function compressInTaskContext(task: Task): Promise<boolean> {
	// Check if auto-condense is enabled
	if (!task.autoCondenseContext) {
		return false
	}

	const modelInfo = task.api.getModel().info
	const contextWindow = modelInfo?.contextWindow || DEFAULT_CONTEXT_WINDOW
	// Use user-configured threshold percentage
	const thresholdPercent = task.autoCondenseContextPercent
	const threshold = Math.floor(contextWindow * (thresholdPercent / 100))

	// 1. Strip injected messages — work only with core conversation
	const coreMessages = task.apiConversationHistory.filter((m) => !m.isContextBlock && !m.isContextSummary)

	if (coreMessages.length < MIN_MESSAGES_FOR_COMPRESSION) {
		return false
	}

	// Count tokens of core messages only
	let coreTokens = 0
	const tokenCounts: number[] = []
	for (const msg of coreMessages) {
		const count = await countMessageTokens(msg)
		tokenCounts.push(count)
		coreTokens += count
	}

	// Also estimate tokens for injected context blocks + summary (Phase 2 will re-inject them)
	const injectedMessages = task.apiConversationHistory.filter((m) => m.isContextBlock || m.isContextSummary)
	let injectedTokens = 0
	for (const msg of injectedMessages) {
		injectedTokens += await countMessageTokens(msg)
	}

	if (coreTokens + injectedTokens <= threshold) {
		return false
	}

	console.log(
		`[AutoCondense] Token count ${coreTokens + injectedTokens} (core: ${coreTokens}, injected: ${injectedTokens}) exceeds threshold ${threshold} (${thresholdPercent}%), triggering backpack+summary compression...`,
	)

	// 2. Create a special summary task folder with "_summary" suffix
	const summaryTimestamp = generateTaskTimestamp() + "_summary"

	// 3. Run context block selection (backpack filling)
	let selectionCount = 0
	let detailedTurns: DetailedTurn[] = []
	try {
		selectionCount = await performContextSelection(task)
		// Persist the selection work as a turn in the summary task folder
		await saveTurnOutput(task.globalStoragePath, task.taskId, summaryTimestamp, "上下文选择", {
			turnNumber: 1,
			timestamp: Date.now(),
			todoItemContent: "上下文选择",
			output: {
				assistantMessage: `Context block selection completed. Evaluated turns from ${coreMessages.length} core messages, selected ${selectionCount} blocks. contextRefsPath=${task.contextRefsPath || "N/A"}`,
				toolCalls: [],
			},
		})
		console.log(`[AutoCondense] Context selection completed: ${selectionCount} blocks selected`)
		// Load detail for UI display
		if (task.contextRefsPath) {
			try {
				const refsContent = await fs.readFile(task.contextRefsPath, "utf8")
				const refsFile = JSON.parse(refsContent) as ContextRefsFile
				detailedTurns = await loadDetailedTurns(task.globalStoragePath, task.taskId, refsFile)
			} catch {
				/* non-critical */
			}
		}
	} catch (err) {
		console.warn("[AutoCondense] Context selection failed (non-critical):", err)
	}

	// 4. Generate summary from turn files on disk
	let contextSummaryText: string | undefined
	try {
		contextSummaryText = await generateSummaryFromTurns(task)
		if (contextSummaryText) {
			await saveContextSummary(task, contextSummaryText, coreMessages.length)
			// Persist the summary work as a turn in the summary task folder
			await saveTurnOutput(task.globalStoragePath, task.taskId, summaryTimestamp, "上下文概括", {
				turnNumber: 1,
				timestamp: Date.now(),
				todoItemContent: "上下文概括",
				output: {
					assistantMessage: contextSummaryText,
					toolCalls: [],
				},
			})
			console.log(`[AutoCondense] Summary generated (${contextSummaryText.length} chars)`)
		}
	} catch (err) {
		console.warn("[AutoCondense] Summary generation failed (non-critical):", err)
	}

	// 5. Find the split point in core messages: keep recent messages under the keep fraction
	const coreBudget = Math.floor(threshold * KEEP_RECENT_FRACTION)
	let keepFromIndex = coreMessages.length
	let keptTokens = 0
	for (let i = coreMessages.length - 1; i >= 0; i--) {
		keptTokens += tokenCounts[i]
		if (keptTokens > coreBudget) {
			keepFromIndex = i + 1
			break
		}
	}

	// Ensure we always keep at least a few recent messages
	keepFromIndex = Math.min(keepFromIndex, coreMessages.length - 4)
	if (keepFromIndex <= 2) {
		return false
	}

	// Ensure we don't split a tool_use/tool_result pair
	if (keepFromIndex < coreMessages.length) {
		const msgAtSplit = coreMessages[keepFromIndex]
		if (
			msgAtSplit.role === "user" &&
			Array.isArray(msgAtSplit.content) &&
			msgAtSplit.content.some((b: any) => b.type === "tool_result")
		) {
			keepFromIndex = Math.max(0, keepFromIndex - 1)
		}
	}

	const messagesToRemove = coreMessages.slice(0, keepFromIndex)
	const messagesToPreserve = coreMessages.slice(keepFromIndex)

	if (messagesToRemove.length < 4) {
		return false
	}

	// 6. Replace history with only preserved core messages.
	//    Phase 2 (injectContextBlocks) will prepend [context blocks] + [summary] on next API call.
	await task.overwriteApiConversationHistory(messagesToPreserve)

	// 7. Assemble the summary task record
	try {
		await assembleTurns(task.globalStoragePath, task.taskId, summaryTimestamp)
	} catch (err) {
		console.warn("[AutoCondense] Failed to assemble summary task:", err)
	}

	console.log(
		`[AutoCondense] Removed ${messagesToRemove.length} old messages (${coreTokens - keptTokens} tokens), kept ${messagesToPreserve.length} recent messages. Summary task: ${summaryTimestamp}. Phase 2 will re-inject context blocks + summary.`,
	)

	// Emit a non-partial condense_context message with detail JSON (same format as todo_item_divider)
	const condenseDetail = JSON.stringify({
		content: `Auto Condense: ${messagesToRemove.length} messages → ${messagesToPreserve.length}`,
		turns: detailedTurns,
		contextSummaryText,
	})
	await task.say("condense_context", condenseDetail, undefined, undefined, undefined, undefined, {
		isNonInteractive: true,
	})

	return true
}

/**
 * Call the compression/condensing model.
 */
async function callCompressionModel(
	apiHandler: ApiHandler,
	systemPrompt: string,
	userMessage: string,
): Promise<string> {
	const messages: Anthropic.Messages.MessageParam[] = [{ role: "user", content: userMessage }]

	let result = ""
	const stream = apiHandler.createMessage(systemPrompt, messages)

	for await (const chunk of stream) {
		if (chunk.type === "text") {
			result += chunk.text
		}
	}

	return result.trim()
}

/**
 * Load the backpack turns + summary detail from disk for UI display.
 * Returns a JSON string with { content, turns, contextSummaryText } or undefined.
 */
export async function loadCondenseDetail(task: Task): Promise<string | undefined> {
	let detailedTurns: DetailedTurn[] = []
	let contextSummaryText: string | undefined

	// Load turns from context_refs.json
	if (task.contextRefsPath) {
		try {
			const refsContent = await fs.readFile(task.contextRefsPath, "utf8")
			const refsFile = JSON.parse(refsContent) as ContextRefsFile
			detailedTurns = await loadDetailedTurns(task.globalStoragePath, task.taskId, refsFile)
		} catch {
			/* non-critical */
		}
	}

	// Load summary from context_summary.json
	if (task.taskTimestamp) {
		try {
			const taskDir = await getTaskDirectoryPath(task.globalStoragePath, task.taskId)
			const summaryPath = path.join(taskDir, "summary", "context", task.taskTimestamp, CONTEXT_SUMMARY_FILENAME)
			const summaryContent = await fs.readFile(summaryPath, "utf8")
			const summaryFile = JSON.parse(summaryContent) as ContextSummaryFile
			contextSummaryText = summaryFile.summaryText
		} catch {
			/* non-critical */
		}
	}

	if (detailedTurns.length === 0 && !contextSummaryText) {
		return undefined
	}

	return JSON.stringify({
		content: `Context Retention: ${detailedTurns.length} turns selected`,
		turns: detailedTurns,
		contextSummaryText,
	})
}

/**
 * Get a display-friendly summary of the context refs for UI display.
 */
export async function getContextRefsSummary(task: Task): Promise<string | undefined> {
	if (!task.contextRefsPath) {
		return undefined
	}

	try {
		const content = await fs.readFile(task.contextRefsPath, "utf8")
		const refsFile = JSON.parse(content) as ContextRefsFile

		if (!refsFile.selectedTurns || refsFile.selectedTurns.length === 0) {
			return undefined
		}

		const lines = refsFile.selectedTurns.map((ref) => {
			const label = ref.todoItemContent
				? `Turn ${ref.turnNumber} [${ref.todoItemContent}]`
				: `Turn ${ref.turnNumber}`
			return ref.reason ? `• ${label}: ${ref.reason}` : `• ${label}`
		})

		return `已引用 ${refsFile.selectedTurns.length} 条历史消息:\n${lines.join("\n")}`
	} catch {
		return undefined
	}
}
